/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.thriftfs.api;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class MetricsContext implements TBase, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("MetricsContext");
  private static final TField NAME_FIELD_DESC = new TField("name", TType.STRING, (short)1);
  private static final TField IS_MONITORING_FIELD_DESC = new TField("isMonitoring", TType.BOOL, (short)2);
  private static final TField PERIOD_FIELD_DESC = new TField("period", TType.I32, (short)3);
  private static final TField RECORDS_FIELD_DESC = new TField("records", TType.MAP, (short)4);

  public String name;
  public static final int NAME = 1;
  public boolean isMonitoring;
  public static final int ISMONITORING = 2;
  public int period;
  public static final int PERIOD = 3;
  public Map<String,List<MetricsRecord>> records;
  public static final int RECORDS = 4;

  private final Isset __isset = new Isset();
  private static final class Isset implements java.io.Serializable {
    public boolean isMonitoring = false;
    public boolean period = false;
  }

  public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    put(NAME, new FieldMetaData("name", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(ISMONITORING, new FieldMetaData("isMonitoring", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(PERIOD, new FieldMetaData("period", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(RECORDS, new FieldMetaData("records", TFieldRequirementType.DEFAULT, 
        new MapMetaData(TType.MAP, 
            new FieldValueMetaData(TType.STRING), 
            new ListMetaData(TType.LIST, 
                new StructMetaData(TType.STRUCT, MetricsRecord.class)))));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(MetricsContext.class, metaDataMap);
  }

  public MetricsContext() {
  }

  public MetricsContext(
    String name,
    boolean isMonitoring,
    int period,
    Map<String,List<MetricsRecord>> records)
  {
    this();
    this.name = name;
    this.isMonitoring = isMonitoring;
    this.__isset.isMonitoring = true;
    this.period = period;
    this.__isset.period = true;
    this.records = records;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MetricsContext(MetricsContext other) {
    if (other.isSetName()) {
      this.name = other.name;
    }
    __isset.isMonitoring = other.__isset.isMonitoring;
    this.isMonitoring = other.isMonitoring;
    __isset.period = other.__isset.period;
    this.period = other.period;
    if (other.isSetRecords()) {
      Map<String,List<MetricsRecord>> __this__records = new HashMap<String,List<MetricsRecord>>();
      for (Map.Entry<String, List<MetricsRecord>> other_element : other.records.entrySet()) {

        String other_element_key = other_element.getKey();
        List<MetricsRecord> other_element_value = other_element.getValue();

        String __this__records_copy_key = other_element_key;

        List<MetricsRecord> __this__records_copy_value = new ArrayList<MetricsRecord>();
        for (MetricsRecord other_element_value_element : other_element_value) {
          __this__records_copy_value.add(new MetricsRecord(other_element_value_element));
        }

        __this__records.put(__this__records_copy_key, __this__records_copy_value);
      }
      this.records = __this__records;
    }
  }

  @Override
  public MetricsContext clone() {
    return new MetricsContext(this);
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void unsetName() {
    this.name = null;
  }

  // Returns true if field name is set (has been asigned a value) and false otherwise
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public boolean isIsMonitoring() {
    return this.isMonitoring;
  }

  public void setIsMonitoring(boolean isMonitoring) {
    this.isMonitoring = isMonitoring;
    this.__isset.isMonitoring = true;
  }

  public void unsetIsMonitoring() {
    this.__isset.isMonitoring = false;
  }

  // Returns true if field isMonitoring is set (has been asigned a value) and false otherwise
  public boolean isSetIsMonitoring() {
    return this.__isset.isMonitoring;
  }

  public void setIsMonitoringIsSet(boolean value) {
    this.__isset.isMonitoring = value;
  }

  public int getPeriod() {
    return this.period;
  }

  public void setPeriod(int period) {
    this.period = period;
    this.__isset.period = true;
  }

  public void unsetPeriod() {
    this.__isset.period = false;
  }

  // Returns true if field period is set (has been asigned a value) and false otherwise
  public boolean isSetPeriod() {
    return this.__isset.period;
  }

  public void setPeriodIsSet(boolean value) {
    this.__isset.period = value;
  }

  public int getRecordsSize() {
    return (this.records == null) ? 0 : this.records.size();
  }

  public void putToRecords(String key, List<MetricsRecord> val) {
    if (this.records == null) {
      this.records = new HashMap<String,List<MetricsRecord>>();
    }
    this.records.put(key, val);
  }

  public Map<String,List<MetricsRecord>> getRecords() {
    return this.records;
  }

  public void setRecords(Map<String,List<MetricsRecord>> records) {
    this.records = records;
  }

  public void unsetRecords() {
    this.records = null;
  }

  // Returns true if field records is set (has been asigned a value) and false otherwise
  public boolean isSetRecords() {
    return this.records != null;
  }

  public void setRecordsIsSet(boolean value) {
    if (!value) {
      this.records = null;
    }
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case ISMONITORING:
      if (value == null) {
        unsetIsMonitoring();
      } else {
        setIsMonitoring((Boolean)value);
      }
      break;

    case PERIOD:
      if (value == null) {
        unsetPeriod();
      } else {
        setPeriod((Integer)value);
      }
      break;

    case RECORDS:
      if (value == null) {
        unsetRecords();
      } else {
        setRecords((Map<String,List<MetricsRecord>>)value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case NAME:
      return getName();

    case ISMONITORING:
      return new Boolean(isIsMonitoring());

    case PERIOD:
      return new Integer(getPeriod());

    case RECORDS:
      return getRecords();

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case NAME:
      return isSetName();
    case ISMONITORING:
      return isSetIsMonitoring();
    case PERIOD:
      return isSetPeriod();
    case RECORDS:
      return isSetRecords();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MetricsContext)
      return this.equals((MetricsContext)that);
    return false;
  }

  public boolean equals(MetricsContext that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_isMonitoring = true;
    boolean that_present_isMonitoring = true;
    if (this_present_isMonitoring || that_present_isMonitoring) {
      if (!(this_present_isMonitoring && that_present_isMonitoring))
        return false;
      if (this.isMonitoring != that.isMonitoring)
        return false;
    }

    boolean this_present_period = true;
    boolean that_present_period = true;
    if (this_present_period || that_present_period) {
      if (!(this_present_period && that_present_period))
        return false;
      if (this.period != that.period)
        return false;
    }

    boolean this_present_records = true && this.isSetRecords();
    boolean that_present_records = true && that.isSetRecords();
    if (this_present_records || that_present_records) {
      if (!(this_present_records && that_present_records))
        return false;
      if (!this.records.equals(that.records))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case NAME:
          if (field.type == TType.STRING) {
            this.name = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ISMONITORING:
          if (field.type == TType.BOOL) {
            this.isMonitoring = iprot.readBool();
            this.__isset.isMonitoring = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case PERIOD:
          if (field.type == TType.I32) {
            this.period = iprot.readI32();
            this.__isset.period = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case RECORDS:
          if (field.type == TType.MAP) {
            {
              TMap _map23 = iprot.readMapBegin();
              this.records = new HashMap<String,List<MetricsRecord>>(2*_map23.size);
              for (int _i24 = 0; _i24 < _map23.size; ++_i24)
              {
                String _key25;
                List<MetricsRecord> _val26;
                _key25 = iprot.readString();
                {
                  TList _list27 = iprot.readListBegin();
                  _val26 = new ArrayList<MetricsRecord>(_list27.size);
                  for (int _i28 = 0; _i28 < _list27.size; ++_i28)
                  {
                    MetricsRecord _elem29;
                    _elem29 = new MetricsRecord();
                    _elem29.read(iprot);
                    _val26.add(_elem29);
                  }
                  iprot.readListEnd();
                }
                this.records.put(_key25, _val26);
              }
              iprot.readMapEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();


    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.name != null) {
      oprot.writeFieldBegin(NAME_FIELD_DESC);
      oprot.writeString(this.name);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(IS_MONITORING_FIELD_DESC);
    oprot.writeBool(this.isMonitoring);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(PERIOD_FIELD_DESC);
    oprot.writeI32(this.period);
    oprot.writeFieldEnd();
    if (this.records != null) {
      oprot.writeFieldBegin(RECORDS_FIELD_DESC);
      {
        oprot.writeMapBegin(new TMap(TType.STRING, TType.LIST, this.records.size()));
        for (Map.Entry<String, List<MetricsRecord>> _iter30 : this.records.entrySet())        {
          oprot.writeString(_iter30.getKey());
          {
            oprot.writeListBegin(new TList(TType.STRUCT, _iter30.getValue().size()));
            for (MetricsRecord _iter31 : _iter30.getValue())            {
              _iter31.write(oprot);
            }
            oprot.writeListEnd();
          }
        }
        oprot.writeMapEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MetricsContext(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isMonitoring:");
    sb.append(this.isMonitoring);
    first = false;
    if (!first) sb.append(", ");
    sb.append("period:");
    sb.append(this.period);
    first = false;
    if (!first) sb.append(", ");
    sb.append("records:");
    if (this.records == null) {
      sb.append("null");
    } else {
      sb.append(this.records);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

