/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hdfs_constants.h"

namespace hadoop { namespace api {

const hdfsConstants g_hdfs_constants;

hdfsConstants::hdfsConstants() {
  UNKNOWN_THRIFT_PORT = -1;

  QUOTA_DONT_SET = -2LL;

  QUOTA_RESET = -1LL;

}

}} // namespace

